### ISSUE TITLE
Main URL broken (404) ?

### ISSUE THREAD

**Issue by david-jankoski** [futureverse/futureverse.org#2]
I just noticed that the main links to https://www.futureverse.org/ on these pages are broken and lead to 404 pages
https://github.com/futureverse
https://github.com/futureverse/futureverse.org

![Screenshot 2024-06-06 at 11 26 39](https://github.com/futureverse/futureverse.org/assets/17311292/1a333501-5409-4c25-9894-ebcd1d2bb06d)

**Comment by HenrikBengtsson** [comment]
Thanks. Yes, I also noticed this. I moved this repo to another GitHub org yesterday and forgot to update the DNS entry. I've fixed that a hour or so ago, but I guess it'll take some hours to roll out.

**Comment by HenrikBengtsson** [comment]
Ah... there was another bug between my chair and my notebook - forgot to redo setting on GitHub. Now fixed.
